//
//  Product.swift
//  Veterinaria
//
//  Created by David Grau Beltrán  on 20/01/24.
//

import Foundation


struct Product: Identifiable { //product which will conform to the Identifiable protocol, this model will tell the program what varibales each sweater thta we creat must have
    //1st we need to create an ID, which will be a UUID
    var id = UUID() //uuid is automatically generated by swift and it will uniquely identify this item
    //next we also wants to have a name for each product
    var name: String
    var image: String
    var price: Int
    
    
}
//Now that w ecreated our product model, we need to add some dummy data, so we´ll be using the eight dog toys that we added in out Assets folder, and for each one, we'll vreate a product instance
// Let's create a variable called productList And it will be an array of Product
var productList = [Product(name: "Rope With Ball", image: "DogToy_1", price: 340),
                   Product(name: "Bone Dog Toy", image: "DogToy_2", price: 180),
                   Product(name: "Ball", image: "DogToy_3", price: 100),
                   Product(name: "Pickle Dog Toy", image: "DogToy_4", price: 160),
                   Product(name: "Broccoli Dog Toy", image: "DogToy_5", price: 200),
                   Product(name: "Rope With Knots", image: "DogToy_6", price: 100),
                   Product(name: "Chicken Toy", image: "DogToy_7", price: 50),
                   Product(name: "Stuffed Dog", image: "DogToy_8", price: 120)]

 // we select the one (name:image:price)//we don't need to set up the ID because the ID is already set up in the model

